version: '3.4'

services:
  redis:
    image: redis
    restart: always
    command: redis-server --appendonly yes
    ports:
      - 6379:6379
    volumes:
      - ./redis/data:/data
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: seigi
      MONGO_INITDB_ROOT_PASSWORD: seigi@123
    ports:
      - 27017:27017
    #volumes:
      # https://github.com/jsbroks/coco-annotator/issues/30
      #- ./mongo/db:/data/db
      #- ./mongo/configdb:/data/configdb

  mysql:
    image: mysql
    restart: always
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: seigi@123
      MYSQL_DATABASE: test
      TZ: 'Asia/Tokyo'
    ports:
    - 3306:3306
    volumes:
      #- ./mysql/data:/var/lib/mysql
      - ./mysql/init:/docker-entrypoint-initdb.d

  postgres:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=seigi@123
    ports:
      - 5432:5432
    volumes:
      #- ./postgres/data:/var/lib/postgresql/data
      - ./postgres/init:/docker-entrypoint-initdb.d
    