version: '3.4'

services:
  mvc_sample:
    environment:
      - ConnectionString_SQL=Data Source=192.168.0.7;Initial Catalog=Northwind;User ID=sa;Password=seigi@123;
    ports:
      - "80"
      - "443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro